# LABELS

<ClickableLabel@Label>:
    color: "black"
    size_hint: (2/32, 1)

<FastFilterLabel@Label>:
    color: "black"
    size_hint: (3/32, 1)
    text: "Use fast filters:"

<TimeLabel@Label>:
    color: "black"
    halign: "center"
    valign: "center"
    size_hint: (6/32, 1)


# BUTTONS

<TodaysNotesButton@Button>:
    size_hint: (1, 1/4)
    text: "Today's notes"

<ToolbarButton@Button>:
    border: (0, 0, 0, 0)
    size_hint: (2/32, 1)
